version: '3.7'

services:

  api-gateway:
    image: krsingh081206/ms-apigateway:latest
    mem_limit: 500m
    ports:
      - "9191:9191"
    networks:
      - ms-network
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.CLOUD.CONFIG.URI : http://cloud-config:9296
      

  cloud-config:
    image: krsingh081206/ms-cloudconfig:latest
    mem_limit: 400m
    ports:
      - "9296:9296"
    networks:
      - ms-network
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
        
    
  service-registry:
    image: krsingh081206/ms-serviceregistry:latest
    mem_limit: 400m
    ports:
      - "8761:8761"
    networks:
      - ms-network
    environment:
      SPRING.CLOUD.CONFIG.URI : http://cloud-config:9296
      

  product-service:
    image: krsingh081206/ms-productservice:latest
    mem_limit: 700m
    ports:
      - "9001:9001"
    networks:
      - ms-network
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.CLOUD.CONFIG.URI : http://cloud-config:9296
       
  product-service2:
    image: krsingh081206/ms-productservice:latest
    mem_limit: 700m
    ports:
      - "9000:9001"
    networks:
      - ms-network
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.CLOUD.CONFIG.URI : http://cloud-config:9296
  
  order-service:
    image: krsingh081206/ms-orderservice:latest
    mem_limit: 700m
    ports:
      - "9002:9002"
    networks:
      - ms-network
    depends_on:
      - service-registry
      - product-service
      - product-service2
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.CLOUD.CONFIG.URI : http://cloud-config:9296
         
    
networks:
  ms-network:
  
#docker run -p 8761:8761 -d krsingh081206/ms-serviceregistry:latest
#docker run -p 9296:9296 -d krsingh081206/ms-cloudconfig:latest
#docker run -p 9191:9191 -d krsingh081206/ms-apigateway:latest
#docker run -p 9001:9001 -d krsingh081206/ms-productservice:latest
#docker run -p 9002:9002 -d krsingh081206/ms-orderservice:latest
#docker run -p 9191:9191 krsingh081206/ms-apigateway:latest -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE='http://localhost:8761/eureka'
#docker service create  -d --name discovery --network mybridge  --replicas 1 -p 8761:8761 krsingh081206/ms-serviceregistry:latest
#docker service create  -d --name api-gateway --network mybridge  --replicas 1 -p 9191:9191 krsingh081206/ms-apigateway:latest -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE='http://discovery:8761/eureka'