server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:    gateway:      routes:
       - id : ORDER-SERVICE
         uri: lb://ORDER-SERVICE
         predicates:
           - Path=/api/v1/orders/**
         filters:          - name : CircuitBreaker
            args:              name : ORDER-SERVICE
              fallbackuri : forward:/api/v1/orderfallback         - id : PRODUCT-SERVICE
         uri: lb://PRODUCT-SERVICE
         predicates:
           - Path=/api/v1/products/**
         filters:
          - name : CircuitBreaker
            args:
              name : PRODUCT-SERVICE
              fallbackuri : forward:/api/v1/productfallback          



eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
    
       